import { router, json, error, storage } from '@appdeploy/sdk';
import ExcelJS from 'exceljs';
import schoolData from './schools4cre.json';

type SchoolRef={inep:string;sme:string;nome:string};
type Account={programa:string;banco:string;agencia:string;conta:string;saldo:string;ocorrencia:string};
type Finance={destinacao:string;devidoCusteio:string;devidoCapital:string;devidoTotal:string;ajusteCusteio:string;ajusteCapital:string;ajusteTotal:string;finalDevidoTotal:string;pagoCusteio:string;pagoCapital:string;pagoTotal:string;data:string};
type SourceIdentity={inep:string;sme:string;denominacao:string};
type SchoolData={inep:string;sme:string;nome:string;denominacaoFnde:string;uex:string;cnpj:string;accounts:Account[];finance:Finance[];source:string;sourceIdentity:SourceIdentity};

const SCHOOLS=(schoolData as {schools:SchoolRef[]}).schools;
const EXPECTED_COUNT=163;
const OUT_PATH='exports/PDDEInfo_4a_CRE_2026_Visao_Financeira_V2.xlsx';
const headers={'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36','Accept':'text/html,application/xhtml+xml','Accept-Language':'pt-BR,pt;q=0.9','Referer':'https://www.fnde.gov.br/pddeinfo/pddeinfo/escola/consultar'};
const XLSX_HEADERS=['Código INEP','Código SME','Unidade Escolar','UEx','CNPJ UEx','Agência PDDE','Conta PDDE','Status conta PDDE','Observação da validação','Previsto 1ª Parcela','Recebido 1ª Parcela','Data Ordem/Pagamento 1ª Parcela','Previsto 2ª Parcela','Recebido 2ª Parcela','Data Ordem/Pagamento 2ª Parcela','Previsto Primeira Infância P1','Recebido Primeira Infância P1','Data Ordem/Pagamento Primeira Infância P1','Agência PDDE Qualidade','Conta PDDE Qualidade','Previsto Educação Conectada 2026','Recebido Educação Conectada 2026','Data Ordem/Pagamento Educação Conectada 2026','Previsto Escola e Comunidade 2026','Recebido Escola e Comunidade 2026','Data Ordem/Pagamento Escola e Comunidade 2026','Previsto Escola das Adolescências 2026','Recebido Escola das Adolescências 2026','Data Ordem/Pagamento Escola das Adolescências 2026','Previsto Cantinho da Leitura 2026','Recebido Cantinho da Leitura 2026','Data Ordem/Pagamento Cantinho da Leitura 2026','Agência PDDE Equidade','Conta PDDE Equidade','Previsto PDDE SRM 2026','Recebido PDDE SRM 2026','Data Ordem/Pagamento PDDE SRM 2026','Agência Educação Integral','Conta Educação Integral'];

function baseErrors(){const errors:string[]=[];if(SCHOOLS.length!==EXPECTED_COUNT)errors.push(`quantidade ${SCHOOLS.length}`);if(new Set(SCHOOLS.map(x=>x.inep)).size!==EXPECTED_COUNT)errors.push('INEPs duplicados');if(new Set(SCHOOLS.map(x=>x.sme)).size!==EXPECTED_COUNT)errors.push('códigos SME duplicados');if(SCHOOLS.some(x=>!/^\d{8}$/.test(x.inep)))errors.push('INEP inválido');if(SCHOOLS.some(x=>!/^04\d{5}$/.test(x.sme)))errors.push('código SME fora da 4ª CRE');if(SCHOOLS.some(x=>!x.nome.trim()))errors.push('nome vazio');return errors;}
function fingerprint(){let h=2166136261;const value=SCHOOLS.map(x=>`${x.inep}:${x.sme}:${x.nome}`).join('|');for(let i=0;i<value.length;i++){h^=value.charCodeAt(i);h=Math.imul(h,16777619);}return (h>>>0).toString(16).padStart(8,'0');}
const BASE_ERRORS=baseErrors();
const BASE_FINGERPRINT=fingerprint();

function clean(s:string){return s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,' ').replace(/<style\b[^>]*>[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#0?39;|&apos;/gi,"'").replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&#x([0-9a-f]+);/gi,(_,n)=>String.fromCodePoint(Number.parseInt(n,16))).replace(/&#(\d+);/g,(_,n)=>String.fromCodePoint(Number(n))).replace(/\s+/g,' ').trim();}
function cells(row:string){return Array.from(row.matchAll(/<t[dh]\b[^>]*>([\s\S]*?)<\/t[dh]>/gi)).map(m=>clean(m[1]));}
function score(s:string){const terms=['Programa/Ação','Agência','Município','Destinação','Educação','Prestação'];let n=terms.reduce((a,t)=>a+(s.includes(t)?4:0),0);return n-(s.match(/Ã.|Â.|�/g)||[]).length*3;}
function identity(html:string):SourceIdentity{for(const row of Array.from(html.matchAll(/<tr\b[^>]*>[\s\S]*?<\/tr>/gi)).map(m=>m[0])){const c=cells(row);const ic=c.indexOf('Cod. Escola:');const inn=c.indexOf('Nome Escola:');if(ic>=0&&inn>=0&&c[ic+1]&&c[inn+1]){const inep=c[ic+1].replace(/\D/g,'');const den=c[inn+1];const match=den.match(/^(\d{7})\s+(.+)$/);return {inep,sme:match?.[1]||'',denominacao:den};}}throw new Error('identificação da escola não localizada na resposta');}
function parse(ref:SchoolRef,url:string,html:string,id:SourceIdentity):SchoolData{let uex='';let cnpj='';let mode='';const accounts:Account[]=[];const finance:Finance[]=[];for(const raw of Array.from(html.matchAll(/<tr\b[^>]*>[\s\S]*?<\/tr>/gi)).map(m=>m[0])){const c=cells(raw);if(!c.length)continue;const ie=c.indexOf('Executora:');const ij=c.indexOf('CNPJ:');if(ie>=0&&ij>=0){uex=c[ie+1]||uex;cnpj=c[ij+1]||cnpj;continue;}if(c.includes('Programa/Ação')&&c.includes('Banco')&&c.includes('Agência')&&c.includes('Conta')&&c.includes('Saldo')){mode='bank';continue;}if(c.includes('Destinação')&&c.some(x=>x.includes('Vl Devido Custeio'))){mode='finance';continue;}const joined=c.join(' ');if(joined.includes('Situação da Unidade Executora')||joined.includes('Situação da Entidade Executora')){mode='';continue;}if(mode==='bank'&&c.length>=5&&/^\d{3}$/.test(c[1]))accounts.push({programa:c[0]||'',banco:c[1]||'',agencia:c[2]||'',conta:c[3]||'',saldo:c[4]||'',ocorrencia:c[5]||''});if(mode==='finance'&&c.length>=11&&!['Subtotal','Total Geral','---'].includes(c[0])&&/^-?[\d.]+,\d{2}$/.test(c[1]))finance.push({destinacao:c[0]||'',devidoCusteio:c[1]||'',devidoCapital:c[2]||'',devidoTotal:c[3]||'',ajusteCusteio:c[4]||'',ajusteCapital:c[5]||'',ajusteTotal:c[6]||'',finalDevidoTotal:c[7]||'',pagoCusteio:c[8]||'',pagoCapital:c[9]||'',pagoTotal:c[10]||'',data:c[11]||''});}return {inep:ref.inep,sme:ref.sme,nome:ref.nome,denominacaoFnde:id.denominacao,uex,cnpj,accounts,finance,source:url,sourceIdentity:id};}
async function requestHtml(url:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),10000);try{const response=await fetch(url,{headers,signal:controller.signal});const bytes=new Uint8Array(await response.arrayBuffer());const utf8=new TextDecoder('utf-8').decode(bytes);const latin=new TextDecoder('windows-1252').decode(bytes);const html=score(latin)>score(utf8)?latin:utf8;if(response.status!==200)throw new Error(`HTTP ${response.status}`);return html;}finally{clearTimeout(timer);}}
async function fetchSchool(ref:SchoolRef){const url=`https://www.fnde.gov.br/pddeinfo/pddeinfo/escola/consultar?ano=2026&co_escola=${encodeURIComponent(ref.inep)}&consultar=Consultar`;let last='';for(let attempt=1;attempt<=3;attempt++){try{const html=await requestHtml(url);const id=identity(html);if(id.inep!==ref.inep)throw new Error(`INEP devolvido ${id.inep||'vazio'}`);if(id.sme!==ref.sme)throw new Error(`código SME devolvido ${id.sme||'vazio'}`);return parse(ref,url,html,id);}catch(e){last=e instanceof Error?e.message:String(e);if(attempt<3)await new Promise(resolve=>setTimeout(resolve,400*attempt));}}throw new Error(`${ref.inep}: ${last}`);}
function textValue(value:unknown){if(value===null||value===undefined)return '';if(typeof value==='object'&&value&&'text' in value)return String((value as {text:unknown}).text);return String(value);}
async function validateWorkbook(bytes:Buffer){if(bytes.length<10000||bytes.length>8_000_000)throw new Error('tamanho do XLSX fora do intervalo permitido');if(bytes[0]!==0x50||bytes[1]!==0x4b)throw new Error('assinatura XLSX inválida');const wb=new ExcelJS.Workbook();await wb.xlsx.load(bytes);if(wb.worksheets.length!==2)throw new Error('o arquivo deve conter exatamente duas abas');const main=wb.getWorksheet('Financeiro 4ª CRE V2');const val=wb.getWorksheet('Validação V2');if(!main||!val)throw new Error('abas obrigatórias ausentes');if(main.rowCount!==167||main.columnCount!==39)throw new Error(`dimensão principal inválida: ${main.rowCount}x${main.columnCount}`);for(let c=1;c<=39;c++)if(textValue(main.getCell(4,c).value)!==XLSX_HEADERS[c-1])throw new Error(`cabeçalho divergente na coluna ${c}`);const seen=new Set<string>();let missing=0;for(let i=0;i<SCHOOLS.length;i++){const row=main.getRow(i+5);const ref=SCHOOLS[i];const inep=textValue(row.getCell(1).value);const sme=textValue(row.getCell(2).value);const nome=textValue(row.getCell(3).value);if(inep!==ref.inep||sme!==ref.sme||nome!==ref.nome)throw new Error(`identificação divergente na linha ${i+5}`);if(seen.has(inep))throw new Error(`INEP duplicado no XLSX: ${inep}`);seen.add(inep);const agencia=textValue(row.getCell(6).value);const conta=textValue(row.getCell(7).value);const status=textValue(row.getCell(8).value);if(Boolean(agencia)!==Boolean(conta))throw new Error(`conta PDDE parcial na linha ${i+5}`);if(!agencia){missing++;if(status!=='NÃO INFORMADA PELO PDDEINFO')throw new Error(`status de conta ausente divergente na linha ${i+5}`);}else if(status!=='Informada pelo PDDEInfo')throw new Error(`status de conta informada divergente na linha ${i+5}`);for(const c of [1,2,6,7,19,20,33,34,38,39]){const v=row.getCell(c).value;if(v!==null&&v!==undefined&&typeof v!=='string')throw new Error(`identificador não textual na linha ${i+5}, coluna ${c}`);}for(const c of [10,11,13,14,16,17,21,22,24,25,27,28,30,31,35,36]){const v=row.getCell(c).value;if(v!==null&&v!==undefined&&typeof v!=='number')throw new Error(`valor financeiro inválido na linha ${i+5}, coluna ${c}`);}for(const c of [12,15,18,23,26,29,32,37]){const v=row.getCell(c).value;if(v!==null&&v!==undefined&&!(v instanceof Date))throw new Error(`data inválida na linha ${i+5}, coluna ${c}`);}row.eachCell({includeEmpty:false},cell=>{if(cell.type===ExcelJS.ValueType.Formula)throw new Error(`fórmula não permitida na linha ${i+5}`);});}
if(seen.size!==EXPECTED_COUNT)throw new Error('quantidade de INEPs únicos inválida');const vh=['Código SME','Código INEP','Unidade Escolar','Status conta PDDE','Resultado da auditoria'];for(let c=1;c<=5;c++)if(textValue(val.getCell(19,c).value)!==vh[c-1])throw new Error(`cabeçalho de validação divergente na coluna ${c}`);if(Number(val.getCell('B4').value)!==EXPECTED_COUNT||Number(val.getCell('B5').value)!==EXPECTED_COUNT-missing||Number(val.getCell('B6').value)!==missing||Number(val.getCell('B7').value)!==missing||Number(val.getCell('B8').value)!==0)throw new Error('resumo da validação divergente');const listed=new Set<string>();for(let r=20;r<20+missing;r++){const inep=textValue(val.getCell(r,2).value);if(!inep||listed.has(inep))throw new Error('lista de contas ausentes inválida');listed.add(inep);}if(listed.size!==missing)throw new Error('quantidade de casos na validação divergente');return {missing};}

export const handler=router({
  'GET /api/4cre-meta':[async()=>BASE_ERRORS.length?error(`Base da 4ª CRE inválida: ${BASE_ERRORS.join('; ')}`,500):json({ok:true,valid:true,count:SCHOOLS.length,uniqueInep:new Set(SCHOOLS.map(x=>x.inep)).size,uniqueSme:new Set(SCHOOLS.map(x=>x.sme)).size,allSme04:SCHOOLS.every(x=>x.sme.startsWith('04')),fingerprint:BASE_FINGERPRINT,first:SCHOOLS[0],last:SCHOOLS[SCHOOLS.length-1]})],
  'GET /api/extract-4cre':[async({query})=>{if(BASE_ERRORS.length)return error(`Base da 4ª CRE inválida: ${BASE_ERRORS.join('; ')}`,500);const start=Number(query.start??'0');const count=Number(query.count??'10');if(!Number.isInteger(start)||start<0||start>=SCHOOLS.length)return error('Parâmetro start inválido.',400);if(!Number.isInteger(count)||count<1||count>10)return error('Parâmetro count inválido.',400);const subset=SCHOOLS.slice(start,start+count);const results=await Promise.all(subset.map(async ref=>{try{return {ok:true,data:await fetchSchool(ref)};}catch(e){return {ok:false,inep:ref.inep,sme:ref.sme,error:e instanceof Error?e.message:String(e)};}}));return json({ok:true,start,count:subset.length,total:SCHOOLS.length,fingerprint:BASE_FINGERPRINT,results});}],
  'POST /api/save-xlsx':[async({body})=>{try{const b=body as {content?:string;fingerprint?:string};if(b?.fingerprint!==BASE_FINGERPRINT)return error('Identificador da base da 4ª CRE inválido.',400);if(!b?.content||b.content.length<1000||b.content.length>12_000_000)return error('Conteúdo XLSX ausente ou inválido.',400);const bytes=Buffer.from(b.content,'base64');const audit=await validateWorkbook(bytes);const [ok]=await storage.write([{path:OUT_PATH,content:b.content,contentType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}]);if(!ok)return error('Falha ao persistir o XLSX.',500);const [u]=await storage.url([OUT_PATH]);return json({ok:true,url:u.url,path:OUT_PATH,audit:{schools:EXPECTED_COUNT,columns:39,sheets:2,missing:audit.missing}});}catch(e){return error(`XLSX rejeitado: ${e instanceof Error?e.message:String(e)}`,400);}}],
  'GET /api/latest-xlsx':[async()=>{try{const [u]=await storage.url([OUT_PATH]);return json({ok:true,url:u.url,path:OUT_PATH});}catch(e){return error(`Falha ao obter XLSX: ${e instanceof Error?e.message:String(e)}`,500);}}]
});
