import { describe, expect, test } from 'vitest';
import { buildSigefPublicStatementUrl, classifySigefMovement, decodeSigefHtml, formatSigefAccount, parseSigefPublicPage } from '../../backend/adapters/sigef-public-statement';
const url='https://www.fnde.gov.br/sigefweb/index.php/conta-corrente/extrato-conta-corrente-detalhamento/banco/001/agencia/0249/contacorrente/000056267X/cnpj/01226403000116/programa/02/data/012026';
const html=`<html><body><h1>SIGEF Extrato Conta Corrente</h1><table><tr><th>CNPJ</th><td>01.226.403/0001-16</td><th>Razão Social</th><td>CEC JOAO</td></tr><tr><th>Banco</th><td>001 - Banco do Brasil</td><th>Agência</th><td>0249</td></tr><tr><th>Conta Corrente</th><td>000056267X</td><th>Programa</th><td>02 - PROGRAMA DINHEIRO DIRETO NA ESCOLA</td></tr></table><table><tr><th>Data</th><th>Crédito</th><th>Débito</th><th>Documento</th><th>Histórico</th><th>CNPJ Beneficiário</th><th>Razão Social</th><th>Banco Beneficiário</th><th>Agência Beneficiário</th><th>Conta Corrente Beneficiário</th></tr><tr><td>03/05/2026</td><td>8.575,00</td><td>0</td><td>00000001974995000787</td><td>ORDEM BANCARIA</td><td>01.226.403/0001-16</td><td>CEC JOAO</td><td>001</td><td>0249</td><td>000056267X</td></tr><tr><td>03/05/2026</td><td>0</td><td>8.575,00</td><td>1972</td><td>BB-APLIC C.PRZ-APL.AUT</td><td>-</td><td>-</td><td>-</td><td>-</td><td>-</td></tr></table><div>Exibindo de 1 até 2 de 12</div> <a href="${url}/page/2">2</a></body></html>`;
describe('SIGEF Extrato público',()=>{
 test('preserva X e monta URL determinística',()=>{expect(formatSigefAccount('56.267-X')).toBe('000056267X');expect(buildSigefPublicStatementUrl({cnpj:'01.226.403/0001-16',programCode:'02',account:{bank:'1',agency:'249',number:'56.267-X'},startYear:2026})).toBe(url);});
 test('parsing, classificação e paginação',()=>{const r=parseSigefPublicPage(html,url,{cnpj:'01226403000116',programCode:'02',account:{bank:'001',agency:'0249',number:'000056267X'}});expect(r.declaredTotal).toBe(12);expect(r.pageUrls).toContain(`${url}/page/2`);expect(r.movements[0]).toMatchObject({amountCents:857500,classification:'REPASSE_FNDE',movementDate:'2026-05-03'});expect(r.movements[1].classification).toBe('APLICACAO_FINANCEIRA');});
 test('classificação conservadora',()=>{expect(classifySigefMovement('credit','RENDIMENTO APLICACAO')).toBe('RENDIMENTO_FINANCEIRO');expect(classifySigefMovement('credit','ESTORNO TARIFA')).toBe('ESTORNO_REVERSAO');expect(classifySigefMovement('debit','TARIFA DE EXTRATO')).toBe('TARIFA_BANCARIA');});
 test('decodifica Windows-1252 legado',()=>{const b=Buffer.from('SIGEF Extrato Conta Corrente Cr\xe9dito D\xe9bito Raz\xe3o Social','latin1');expect(decodeSigefHtml(b,null)).toContain('Crédito');});
});
